version: '3.8'
services:
  prometheus:
    image: prom/prometheus
    container_name: watchflix_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring_net

  grafana:
    image: grafana/grafana
    container_name: watchflix_grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring_net
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

networks:
  monitoring_net:
    driver: bridge
