global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'users-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['users-service:8080']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
